name: Unit & Integration tests

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        task:
        - 00.Demo
        - 01.InplaceSorting.s
        - 02.Base85

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv & Python
        uses: ./.github/actions/setup-python-env

      - name: unit test
        working-directory: ${{ matrix.task }}
        run: |
          . ../.venv/bin/activate
          pytest -v *_test.py

      - name: integration test
        working-directory: ${{ matrix.task }}
        run: |
          . ../.venv/bin/activate
          if [ -x "integration_test.sh" ]; then
            ./integration_test.sh
          else
            echo "No executable integration test found, skipping"
          fi
